server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: portfolio-tracker-backend
    static_configs:
      - targets:
          - localhost
        labels:
          job: portfolio-tracker-backend
          __path__: /var/log/portfolio-tracker/app.log

  - job_name: portfolio-tracker-nginx
    static_configs:
      - targets:
          - localhost
        labels:
          job: portfolio-tracker-nginx
          __path__: /var/log/portfolio-tracker/nginx/*.log

  - job_name: portfolio-tracker-system
    static_configs:
      - targets:
          - localhost
        labels:
          job: portfolio-tracker-system
          __path__: /var/log/syslog

  - job_name: docker-containers
    docker_sd_configs:
      - host: unix:///var/run/docker.sock
        refresh_interval: 5s
    relabel_configs:
      - source_labels: ['__meta_docker_container_name']
        regex: '/portfolio-tracker-(.*)'
        target_label: 'container'
      - source_labels: ['__meta_docker_container_log_stream']
        target_label: 'stream'